title: Juan Luis Rivera Ibarra
email: juanluisrivera2@gmail.com
description: >-
  Pagina personal.
baseurl: ""
url: "https://juanluisrivera.github.io/"
github_username:  JuanLuisRivera

collections:
  proyectos:
    output: true
  ejercicios:
    output: true


plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag