title: Juan Luis Rivera Ibarra
email: juanluisrivera2@gmail.com
description: >-
  Pagina personal.
baseurl: ""
url: "https://juanluisrivera.github.io/"
github_username:  JuanLuisRivera

collections:
  proyectos:
    output: true
  ejercicios:
    output: true

# Build settings
#theme: minima

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
