title: Juan Luis Rivera
tagline: Blog dedicado a proyectos personales
description: >-
  Un poco de todo
url: "https://juanluisrivera.github.io/"
author: Juan Luis Rivera Ibarra


collections_dir: collections
collections:
  posts:
    output: true
  ejercicios:
    output: true
  sitios:
    output: true
  solEjercicios:
    output: true
  proyectos:
    output: true
  ejercicios:
    output: true
  lenguajes:
    output: true
  elementosTecnicos:
    output: true

permalink: pretty

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-spaceship

defaults:
  - scope:
      path: ""
      type: "sitios"
    values:
      layout: "sitio"
  - scope:
      path: ""
      type: "ejercicios"
    values:
      layout: "entrada"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "entrada"
  - scope:
      path: ""
      type: "proyectos"
    values:
      layout: "entrada"
  - scope:
      path: ""
      type: "lenguajes"
    values:
      layout: "lenguaje"
  - scope:
      path: ""
      type: "elementosTecnicos"
    values:
      layout: "elementoTecnico"
  - scope:
      path: ""
    values:
      layout: "templates/default"

excerpt_separator: <!--end_excerpt-->