name: Build and Deploy Jekyll Site

on:
  push:
    branches:
      - main  # Replace with your default branch if different

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set Up Ruby Environment
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'  # Adjust to your required Ruby version
          bundler-cache: true   # Caches gems for faster builds

      - name: Install Dependencies
        run: bundle install

      - name: Build the Jekyll Site
        run: bundle exec jekyll build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site
          publish_branch: gh-pages  # You can change this if needed
